dist: bionic

jobs:
  include:
    - stage: 'security audit and linting'
      language: node_js
      # node_js: node version specified in .nvmrc
      install:
        - npm ci
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --config ./audit-ci.json; fi
        - npm run lint
